/**: 
  ros__parameters:
    ocean_current:
      enable: false
      seed: 255
      Vc:
        mu: 0.0
        mean_w: 0.0
        var_w: 0.001
        init_val: 0.0
        min_val: -0.01
        max_val: 0.01
      alpha:
        mu: 0.0
        mean_w: 0.0
        var_w: 0.0001
        init_val: 0.0
        min_val: -0.001
        max_val: 0.001
      beta:
        mu: 0.0
        mean_w: 0.0
        var_w: 0.0001
        init_val: 0.0
        min_val: -0.001
        max_val: 0.001